<h1>Video Site on Zend</h1>

<?php
    print_r($this->url(array('controller'=>'index','action'=>'add')));
?>

<table id="films">
    <thead>
        <tr>
            <th>Film's Name</th>
            <th>Director</th>
            <th></th>
        </tr>
    </thead>

    <?php
    foreach($this->movies as $movie)
    {
        echo '<tr><td>'.$movie->title.'</td>';
        echo '<td>'.$movie->director.'</td><tr>';
    }
    ?>

</table>