<h1>Video Site on Zend</h1>

<?php if ($this->movies): ?>
<table id="films">
    <thead>
        <tr>
            <th>Film's Name</th>
            <th>Director</th>
            <th></th>
        </tr>
    </thead>

    <?php
    foreach($this->movies as $movie)
    {
        echo '<tr><td>'.$this->escape($movie->title).'</td>';
        echo '<td>'.$this->escape($movie->director).'</td>';
        echo '<td><a href='.$this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$movie->id)).'>Edit</a></td>';
        echo '<td><a href='.$this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$movie->id)).'>Delete</a></td></tr>';
    }
    ?>

</table>

<?php else: ?>
<p>No Films in Database</p>

<?php endif;?>
<p><a href='<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>'>Add new film</a></p>